replay_size: 100
gamma: 0.99
lr: &lr_val 1.0e-4
train_every: 100
train_batches: 1
update_after: 1000
batch_size: 100
value_coef: 0.5
entropy_coef: 0.01
max_grad_norm: 0.5
adam_eps: 1.0e-4

controller: 'CentralizedController'
agent: 'ACAgent'
true_reward: False
use_full_obs: False
device: 'cpu'
hidden_layers: [64, 64]
