env_name_index: 2
N_agents: &n_agents 3
env_args:
  grid_width: 5
  grid_height: 12
  N: *n_agents
  max_episode_steps: 100
  levers_prob_self: [[1, 0, 0, 0], [0.7, 0.3, 0, 0], [0.5, 0.25, 0, 0.25], [0, 0, 0, 1]]
  levers_prob_other: [[0, 0.9, 0.0, 0.1], [0.25, 0.05, 0.05, 0.65],[0, 0.5, 0.0, 0.5], [0, 0, 0.6, 0.4]]
total_steps: 10000000
steps_per_epoch: 10000
eval_episodes: 2